services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Root1234"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_server_data:/var/opt/mssql
      - ./script.sql:/script.sql
      - ./sps_prueba.sql:/sps_prueba.sql
      - ./data_dummy.sql:/data_dummy.sql

volumes:
  sql_server_data: